//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace da.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONAN
    {
        public string Mã_món { get; set; }
        public string Tên_món_ăn { get; set; }
        public string công_thức { get; set; }
        public string Mã_tỉnh_thành { get; set; }
    
        public virtual TINH_THANH TINH_THANH { get; set; }
    }
}
